export default {
  overwrite: false,
  formats: [
    'chatgpt-codex',
    'claude',
    'cline',
    'codex',
    'cursor',
    'gemini',
    'kiro',
    'vscode',
    'windsurf'
  ],
  formats_dict: {
    "chatgpt-codex": { filename: 'AGENTS.md' },
    "claude": { filename: '.claude/memories/copy-agent-rule.md' },
    "cline": { filename: '.clinerules/copy-agent-rule.md' },
    "codex": { filename: 'codex.md' },
    "cursor": { filename: '.cursor/rules/copy-agent-rule.mdc', prepend: `---\ndescription: "Generated by copy-agent-rules"\nalwaysApply: true\n---` },
    "gemini": { filename: '.gemini/memories/copy-agent-rule.md' },
    "kiro": { filename: '.kiro/steering/copy-agent-rule.md' },
    "vscode": { filename: '.github/instructions/copy-agent-rule.instructions.md' },
    "windsurf": { filename: '.windsurf/rules/copy-agent-rule.md' }
  },
};

